# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9d38d4209c415a19a0fd517cbb5c2120bfaa534411ef4c07b70d17908c3e083449596da44c76ff3c3abc8c69c083a3e4089eb9d7b56a4c5d9b7331726b4ce6d0

test:
  secret_key_base: 9a4336656f5233284ba7c0d6458f585881b03022a06dfba73652d135729b43fde4d2e6ba8b447808482e382db5d92bb4fcfbea8e57a4a314b6b3fd287b0d3a86

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
